name: 👷 CI/CD (Node.JS)

on:
  workflow_dispatch:
  pull_request:
    paths:
      - '/src/'
  push:
    branches: [ master ]
    paths:
      - '/src/'

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node: [16.x, 18.x]

    steps:
    - uses: actions/checkout@v4
      with:
        node-version: 20
        cache: 'pnpm'

    - uses: pnpm/action-setup@v2
      with:
        version: 8.15.4

    - uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node }}

    - run: npm ci

    - run: npm test

    - run: npm run build
