name: 👷 CI/CD (Node.JS)

on:
  workflow_dispatch:
  pull_request:
    paths:
      - '/src/'
  push:
    branches: [ master ]
    paths:
      - '/src/'

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node: [16.x, 18.x]

    steps:
    - name: Install libvips (Ubuntu)
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update -y
        sudo apt-get install -y libvips git-lfs

    - name: Inicializar Github Action
      uses: actions/checkout@v4

    - name: Instalar Node.js ${{ matrix.node }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node }}

    - name: Instalar dependencias
      run: npm ci

    - name: Análisis lint
      run: npm test

    - name: Construir sitio
      run: npm run build
